CREATE TABLE STUDENT ( 
USN VARCHAR (10) PRIMARY KEY,  
SNAME VARCHAR (25),  
ADDRESS VARCHAR (25),  
PHONE BIGINT (10),  
GENDER CHAR (1)); 

CREATE TABLE SEMSEC ( 
SSID VARCHAR (5) PRIMARY KEY,  
SEM INTEGER (2),  
SEC CHAR (1)); 

CREATE TABLE CLASS ( 
USN VARCHAR (10),  
SSID VARCHAR (5), 
PRIMARY KEY (USN, SSID), 
FOREIGN KEY (USN) REFERENCES STUDENT (USN), 
FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID));

CREATE TABLE SUBJECT ( 
SUBCODE VARCHAR (8),  
TITLE VARCHAR (20),  
SEM INTEGER (2),  
CREDITS INTEGER (2), 
PRIMARY KEY (SUBCODE)); 

CREATE TABLE IAMARKS ( 
USN VARCHAR (10),  
SUBCODE VARCHAR (8),  
SSID VARCHAR (5),  
TEST1 INTEGER (2),  
TEST2 INTEGER (2),  
TEST3 INTEGER (2),  
FINALIA INTEGER (2), 
PRIMARY KEY (USN, SUBCODE, SSID), 
FOREIGN KEY (USN) REFERENCES STUDENT (USN), 
FOREIGN KEY (SUBCODE) REFERENCES SUBJECT (SUBCODE), 
FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID)); 

DESC STUDENT; 
DESC SEMSEC; 
DESC CLASS;
DESC SUBJECT; 
DESC IAMARKS;
