CREATE TABLE STUDENT ( 
USN VARCHAR (10) PRIMARY KEY, 
SNAME VARCHAR (25), 
ADDRESS VARCHAR (25), 
PHONE BIGINT (10), 
GENDER CHAR (1)); 

CREATE TABLE SEMSEC ( 
SSID VARCHAR (5) PRIMARY KEY, 
SEM INT (5), 
SEC CHAR (1)); 

CREATE TABLE CLASS ( 
USN VARCHAR (10), 
SSID VARCHAR (5), 
PRIMARY KEY (USN, SSID), 
FOREIGN KEY (USN) REFERENCES STUDENT (USN), 
FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID)); 

CREATE TABLE SUBJECT( 
SUBCODE VARCHAR(10) 
PRIMARY KEY, 
TITLE VARCHAR(20), 
SEM INT, 
CREDITS INT); 

CREATE TABLE IAMARKS ( 
USN VARCHAR (10), 
SUBCODE VARCHAR (8), 
SSID VARCHAR (5), 
TEST1 INT (2), 
TEST2 INT (2), 
TEST3 INT (2), 
FINALIA INT (2), 
PRIMARY KEY (USN, SUBCODE, SSID), 
FOREIGN KEY (USN) REFERENCES STUDENT (USN), 
FOREIGN KEY (SUBCODE) REFERENCES SUBJECT (SUBCODE), FOREIGN 
KEY (SSID) REFERENCES SEMSEC (SSID));

DESC STUDENT; 
DESC SEMSEC; 
DESC CLASS;
DESC SUBJECT; 
DESC IAMARKS;
